production:
  onboarding_check:
    class: OnboardingHelperJob
    args: []
    queue: default
    schedule: every day at 10:00am
    command: |
      User.where("created_at > ?", 3.days.ago).find_each do |user|
        OnboardingHelperJob.perform_later(user.id)
      end